# Generated by Django 2.2.3 on 2019-07-30 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20190729_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
